### ISSUE TITLE
Resource Not Found "rosbridge_server"

### ISSUE THREAD

**Issue by huyle-anh** [cipherdev/src#1]
Run roslaunch then return not found rosbridge_server
Logs:
```
Resource not found: rosbridge_server
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home0/ampsw/Downloads/cds/src
ROS path [2]=/opt/ros/melodic/share
The traceback for the exception was written to the log file
```

**Comment by huyle-anh** [comment]
Missing the install. So re-install:

> sudo apt-get install ros-melodic-rosbridge-server

--HuyLe

**Comment by JaeYoungLee79** [comment]
It is not change

--------------------------------------
rut21@rut21-370E5L-371B5L:~/catkin_workspace/src/ros_kortex/kortex_driver/launch$ roslaunch kortex_driver.launch 
... logging to /home/rut21/.ros/log/e5152e06-6703-11ec-9452-00c2c6cfd7c1/roslaunch-rut21-370E5L-371B5L-2469.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: kortex_description
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
The traceback for the exception was written to the log file
