### ISSUE TITLE
Catkin_Make fail with cv_bridge not found

### ISSUE THREAD

**Issue by huyle-anh** [cipherdev/src#13]
Logs:
```
-- ==> add_subdirectory(lane_detect)
CMake Error at /opt/ros/melodic/share/cv_bridge/cmake/cv_bridgeConfig.cmake:113 (message):
  Project 'cv_bridge' specifies '/usr/include/opencv' as an include dir,
  which is not found.  It does neither exist as an absolute directory nor in
  '/opt/ros/melodic//usr/include/opencv'.  Check the issue tracker
  'https://github.com/ros-perception/vision_opencv/issues' and consider
  creating a ticket if the problem has not been reported yet.
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  lane_detect/CMakeLists.txt:6 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/cds/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/cds/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```

**Comment by huyle-anh** [comment]
Re-check compile with vision_opencv source with internal libs as success
bellow the step:
```
cd ~/catkin_ws/src
git clone https://github.com/ros-perception/vision_opencv
cd ~/catkin_ws
catkin_make
source devel/setup.bash
```

**Comment by huyle-anh** [comment]
Rootcause not found /usr/include/opencv folder.
Try to install opencv make set `CMAKE_INSTALL_PREFIX ` as /usr/include instead /usr/local/include. 
`
https://answers.opencv.org/question/121885/cant-find-opencvhpp-however-it-is-not-installed-in-usrinclude/
`

**Comment by Rorywh** [comment]
Thanks, It helps a lot.

**Comment by srike27** [comment]
> Rootcause not found /usr/include/opencv folder.
> Try to install opencv make set `CMAKE_INSTALL_PREFIX ` as /usr/include instead /usr/local/include.
> `https://answers.opencv.org/question/121885/cant-find-opencvhpp-however-it-is-not-installed-in-usrinclude/`

Or you can got to /opt/ros/melodic/share/cv_bridge/cmake/cv_bridgeConfig.cmake and add /usr/include as one of the included_dirs
